language: node_js

sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm32v7
    - ARCH=arm64v8

before_script: chmod +x ./travis-build.sh

script:
  - ./travis-build.sh
