sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=arm   QEMU=qemu-arm-static     BASE_IMAGE=arm32v7/debian:jessie-slim
    - ARCH=arm64 QEMU=qemu-aarch64-static BASE_IMAGE=arm64v8/debian:jessie-slim

script:
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
