sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=arm BASE_IMAGE=arm32v7/debian:jessie-slim
    # - ARCH=amd64 BASE_IMAGE=amd64/debian:jessie-slim


script:
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
