sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm32v7

script:
  - chmod +x ./travis-build.sh
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
