sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm32v7


before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - chmod +x ./travis-build.sh

script:
  - ./travis-build.sh
