sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=arm   QEMU=qemu-arm-static     BASE_IMAGE=arm32v7/debian:jessie-slim
    - ARCH=arm64 QEMU=qemu-aarch64-static BASE_IMAGE=arm64v8/debian:jessie-slim
    - ARCH=amd64 QEMU=qemu-fake-static    BASE_IMAGE=amd64/debian:jessie-slim

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - sudo service docker stop
  - sudo apt-cache madison docker-ce
  - sudo apt-get install docker-ce=17.11.0~ce-0~ubuntu
  - docker version

script:
  - ./travis-test.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-build.sh
      ./travis-deploy.sh
    fi
