sudo: required

services:
 - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm32v7
    - ARCH=arm64v8

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  - chmod +x ./travis-build.sh
  - ./travis-build.sh
