version: '3.3'

volumes:
  node_modules:
    driver: local


services:

  test-app:
    build:
      context: .
    environment:
      - REDIS_HOST=redis://redis
    command: npm test
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  redis:
    image: redis
    ports:
      - "6379:6379"
