version: '3.3'

volumes:
  node_modules:
    driver: local


services:

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis://redis-db
    volumes:
      - node_modules:/usr/src/app/node_modules

  test-app:
    build:
      context: .
    environment:
      - REDIS_HOST=redis://redis-db
    command: npm test
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  redis-db:
    image: redis
    ports:
      - "6379:6379"
