version: '3.3'

volumes:
  node_modules:
    driver: local


services:

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app

  test-app:
    build:
      context: .
    command: npm test
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./:/usr/src/app


  redis:
    image: redis
    ports:
      - "6379:6379"
